"""Add unique constraint to ticker+timestamp in tickers_data

Revision ID: 16eeae790ac7
Revises: bcb0dd3c5c9b
Create Date: 2025-07-10 17:57:56.616984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16eeae790ac7'
down_revision: Union[str, Sequence[str], None] = 'bcb0dd3c5c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ticker_timestamp', 'tickers_data', ['ticker', 'timestamp'])
    op.add_column('tickers_signals', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_tickers_signals_created_at'), 'tickers_signals', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_signals_created_at'), table_name='tickers_signals')
    op.drop_column('tickers_signals', 'created_at')
    op.drop_constraint('uq_ticker_timestamp', 'tickers_data', type_='unique')
    # ### end Alembic commands ###
