"""Add unique constraint to ticker+timestamp in tickers_data

Revision ID: 20d54faa5e8f
Revises: 16eeae790ac7
Create Date: 2025-07-10 17:59:00.705173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d54faa5e8f'
down_revision: Union[str, Sequence[str], None] = '16eeae790ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
